from .simple_template import simple_template
from .augment_template import *
from .oxfordpets_template import *
from .flowers102_template import *
from .eurosat_template import *
from .dissertation_template import *
from .fish_template import *
from .marine_template import *
from .ucm_template import *
from .flowers_template import *